<?php
/** @var App\Model\Blog $blog */
/** @var App\Model\Image $thumbnail */
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <meta name="title" content="<?= $blog->getMetaTitle() ?>">
    <meta name="keywords" content="<?= $blog->getMetaKeyword() ?>">
    <meta name="description" content="<?= $blog->getMetaDescription() ?>">
    <meta name="thumbnail" content="<?= $thumbnail->getValue() ?>"
    <title><?= $blog->getTitle() ?> | NGSLab</title>
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" type="text/javascript"></script>
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />
    <script>
        $(function () {
            $("#footer").load("/templates/componenetns/footer.html");
        });
    </script>
</head>

<body>
    <style>
        .archive-listing {
            display: flex;
            align-items: left;
            flex-direction: column;
            box-sizing: border-box;
            padding-left: 30px;
        }

        .blog-card-wrapper {
            width: 60%;
            margin-bottom:30px;
        }

        .blog-card {
            width: 100%;
            height: 150px;
            display: flex;
            flex-direction: row;
            justify-content: space-evenly;
            text-decoration: none;
            color: black;
        }

        .blog-card img {
            height: 150px;
            width: 300px;
            object-fit: cover;
        }

        .blog-card .info-section {
            margin-left: 20px;
        }

        .blog-card .blog-title {
            font-size: 2em;
            font-weight: 700;
            padding: 0px 0px 15px 0px;
        }

        .brief {
            font-weight: 300;
        }

        @media screen and (max-width: 1368px) {
            .archive-listing {
                display: flex;
                align-items: center;
                flex-direction: column;
                padding-left: 0px;
            }

            .blog-card-wrapper {
                height: auto;
                width: 95%;
                margin-bottom: 50px;
            }

            .blog-card {
                flex-direction: column;
                height: auto;
            }

            .blog-card img {
                width: 100%;
                height: auto;
            }

            .blog-card .info-section {
                margin: 0;
            }

        }
    </style>

    <div id="nav"> <?php \App\ViewModel\View::renderComponent('nav.html') ?> </div>
    <div class="blog-wrapper" style="width: 60vw; margin: auto;">
        <?= $blog->getBody() ?>
    </div>
    <div id="footer"></div>
</body>

</html>