<?php

use Diversen\Lang;

/** @var App\Model\Blog[] $blogs */
/** @var App\Model\Blog[] $blogHighlights */
/** @var App\Model\Image[] $blogImages */
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <title>Blogs | NGSLab</title>
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" type="text/javascript"></script>
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />
    <script>
        $(function () {
            $("#footer").load("/templates/componenetns/footer.html");
        });
    </script>
</head>

<body>
    <style>
        #blog-nav{color:#23af4d;}
        .archive-listing {
            display: flex;
            align-items: left;
            flex-direction: column;
            box-sizing: border-box;
            padding: 30px;
        }

        .blog-card-wrapper {
            min-width: 60%;
            margin-bottom:30px;
        }

        .blog-card {
            width: 100%;
            height: 150px;
            display: flex;
            flex-direction: row;
            justify-content: left;
            text-decoration: none;
            color: black;
            margin-left:30px;
        }

        .blog-card img {
            height: 150px;
            width: 300px;
            object-fit: cover;
            border-radius:15px;
        }

        .blog-card .info-section {
            margin-left: 20px;
            box-sizing: border-box;
            padding-top: 10px;
            width: calc(100% - 320px);
        }

        .blog-card .blog-title {
            font-size: 1.8em;
            font-weight: 700;
            padding: 0px 0px 15px 0px;
        }

        .brief {
            font-weight: 300;
        }

        .highlighted-section{
            width:100%;
            display:flex;
            flex-direction:column;
            align-items:center;
        }
        .latest-item{
            width:90%;
            height:33.46vw;
            border-radius:30px;
            display:flex;
            flex-direction:row;
            align-items:flex-start;
            justify-content:space-between;
            text-decoration:none;
            color:black;
        }

        .main-image{
            height: 33.46vw;
            width: 59.5vw;
            content-fit:cover;
            border-radius:30px;
        }

        .main-description{
            width: 27%;
            height:100%;
        }

        .main-description p{
            font-size:1.3em;
        }

        .two-items{
            width:90%;
            height:37vw;
            display:flex;
            flex-direction:row;
            justify-content:space-between;
            align-items:center;
        }

        .item{
            width:40vw;
            height:100%;
            border-radius:30px;
            text-decoration:none;
            color:black;
        }

        .small-image{
            width:40vw;
            height:22.5vw;
            border-radius:30px;
            object-fit: cover;
        }

        .item-description{
            dispay:flex;
            flex-direction:column;
            align-items:left;
            justify-content:space-between;
            box-sizing:border-box;
            padding-left:15px;
            padding-right:15px;

        }
        .blog-card-wrapper:nth-child(1) {
            display: none;
        }
        .blog-card-wrapper:nth-child(2) {
            display: none;
        }
        .blog-card-wrapper:nth-child(3) {
            display: none;
        }

        @media screen and (max-width: 738px) {
            .blog-card-wrapper:nth-child(1) {
                display: flex;
            }
            .blog-card-wrapper:nth-child(2) {
                display: flex;
            }
            .blog-card-wrapper:nth-child(3) {
                display: flex;
            }

            .archive-listing {
                display: flex;
                align-items: center;
                flex-direction: column;
                padding: 0px;
            }

            .blog-card-wrapper {
                height: auto;
                width: 95%;
                margin:0;
                margin-bottom: 50px;
                display: flex;
                flex-direction:column;
                justify-content:center;
                align-items:center;
            }

            .blog-archive-wrapper{
                display:flex;
                flex-direction:column;
                align-items:center;
            }
            .blog-card {
                flex-direction: column;
                justify-content:center;
                height: auto;
                width:auto;
                margin-left:0px;
            }

            .blog-card img {
                width: 95vw;
                height: 47vw!important;
                height: auto;
                border-radius:5px;
            }

            .blog-card .info-section {
                margin: 0;
                box-sizing: border-box;
                padding-left: 10px;
                padding-right: 10px;
                width:auto;
            }

            .highlighted-section{
                display:none;
            }

        }
    </style>

    <div id="nav"> <?php \App\ViewModel\View::renderComponent('nav.phtml') ?> </div>
    <div class="page-title">
    </div>
    <div class="archive-listing">
        <?php $mainBlog = $blogHighlights[0] ?? null ?>
        <?php $secondaryBlog1 = $blogHighlights[1] ?? null ?>
        <?php $secondaryBlog2 = $blogHighlights[2] ?? null?>


        <?php if (isset($mainBlog)): ?>
            <div class="highlighted-section">
                <a class="latest-item" href="<?= \App\Helper\Url::getUrl('/blog/page?id=' . $mainBlog->getId()) ?>">
                    <?= $blogImages[$mainBlog->getId()]->toHtml('main-image'); ?>
                    <div class="main-description">
                        <h1> <?= $mainBlog->getTitle() ?> </h1>
                        <p> <?= $mainBlog->getDescription() ?> </p>
                    </div>
                </a>
                <br><br>
                <?php if (isset($secondaryBlog1)): ?>
                    <div class="two-items">
                        <a class="item1 item" href="<?= \App\Helper\Url::getUrl('/blog/page?id=' . $secondaryBlog1->getId()) ?>">
                            <?= $blogImages[$secondaryBlog1->getId()]->toHtml('small-image'); ?>
                            <div class="item-description">
                                <h1> <?= $secondaryBlog1->getTitle() ?> </h1>
                                <p> <?= $secondaryBlog1->getDescription() ?> </p>
                            </div>
                        </a>
                        <?php if (isset($secondaryBlog2)): ?>
                            <a href="<?= \App\Helper\Url::getUrl('/blog/page?id=' . $secondaryBlog2->getId()) ?>" class="item2 item">
                                <?= $blogImages[$secondaryBlog2->getId()]->toHtml('small-image'); ?>
                                <div class="item-description">
                                    <h1> <?= $secondaryBlog2->getTitle() ?> </h1>
                                    <p> <?= $secondaryBlog2->getDescription() ?> </p>
                                </div>
                            </a>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
            </div>
        <?php endif; ?>
        <br><br>
        <h1 style="padding-left:30px" >
            <?= Lang::translate('BLOG ARCHIVE'); ?>
            <hr>
        </h1>
        <br><br>
        <div class="blog-archive-wrapper">
            <?php foreach ($blogs as $blog): ?>
                <div class="blog-card-wrapper">
                    <a href="<?= \App\Helper\Url::getUrl('/blog/page?id=' . $blog->getId()) ?>" class="blog-card">
                        <?= $blogImages[$blog->getId()]->toHtml() ?>
                        <div class="info-section">
                            <div class="blog-title"> <?= $blog->getTitle() ?> </div>
                            <div class="brief"> <?= $blog->getDescription() ?> </div>
                        </div>
                    </a>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <div id="footer"></div>
</body>

</html>