<?php
    use Diversen\Lang;
/** @var App\Model\Blog[] $blogs */
/** @var App\Model\Image[] $blogImages */
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <title>Blogs | NGSLab</title>
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" type="text/javascript"></script>
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />
    <script>
        $(function () {
            $("#footer").load("/templates/componenetns/footer.html");
        });
    </script>
</head>

<body>
    <style>
        .archive-listing {
            display: flex;
            align-items: left;
            flex-direction: column;
            box-sizing: border-box;
            padding: 30px;
        }

        .blog-card-wrapper {
            width: 60%;
            margin-bottom:30px;
        }

        .blog-card {
            width: 100%;
            height: 150px;
            display: flex;
            flex-direction: row;
            justify-content: left;
            text-decoration: none;
            color: black;
        }

        .blog-card img {
            height: 150px;
            width: 300px;
            object-fit: cover;
        }

        .blog-card .info-section {
            margin-left: 20px;
        }

        .blog-card .blog-title {
            font-size: 2em;
            font-weight: 700;
            padding: 0px 0px 15px 0px;
        }

        .brief {
            font-weight: 300;
        }

        .highlighted-section{
            width:100%;
            display:flex;
            flex-direction:column;
            align-items:center;
        }
        .latest-item{
            width:85%;
            height:65vh;
            border-radius:30px;
            display:flex;
            flex-direction:row;
            align-items:center;
            justify-content:space-between;
            text-decoration:none;
            color:black;
        }

        .main-image{
            height:100%;
            width:70%;
            content-fit:cover;
            border-radius:30px;
        }

        .main-description{
            width: 27%;
            height:100%;
        }

        .main-description p{
            font-size:1.3em;
        }

        .two-items{
            width:85%;
            height:60vh;
            display:flex;
            flex-direction:row;
            justify-content:space-between;
            align-items:center;
        }

        .item{
            width:45%;
            height:100%;
            border-radius:30px;
            text-decoration:none;
            color:black;
        }

        .small-image{
            width:100%;
            height:35vh;
            border-radius:30px;
        }

        .item-description{
            dispay:flex;
            flex-direction:column;
            align-items:left;
            justify-content:space-between;

        }
        .blog-card-wrapper:nth-child(1) {
            display: none;
        }
        .blog-card-wrapper:nth-child(2) {
            display: none;
        }
        .blog-card-wrapper:nth-child(3) {
            display: none;
        }

        @media screen and (max-width: 738px) {
            .blog-card-wrapper:nth-child(1) {
                display: flex;
            }
            .blog-card-wrapper:nth-child(2) {
                display: flex;
            }
            .blog-card-wrapper:nth-child(3) {
                display: flex;
            }

            .archive-listing {
                display: flex;
                align-items: center;
                flex-direction: column;
                padding-left: 0px;
            }

            .blog-card-wrapper {
                height: auto;
                width: 95%;
                margin-bottom: 50px;
                display: flex;
                flex-direction:column;
                justify-content:center;
                align-items:center;
            }

            .blog-card {
                flex-direction: column;
                justify-content:center;
                height: auto;
                width:auto;
            }

            .blog-card img {
                width: 100%;
                height: auto;
            }

            .blog-card .info-section {
                margin: 0;
            }

            .highlighted-section{
                display:none;
            }

        }
    </style>

    <div id="nav"> <?php \App\ViewModel\View::renderComponent('nav.phtml') ?> </div>
    <div class="page-title">
    </div>
    <div class="archive-listing">
       
        <div class="highlighted-section">
            <a class="latest-item" href="#">
                <img class="main-image" src="https://i.pinimg.com/originals/9a/7c/fb/9a7cfb72bee5b42e2daa8ae46cff241a.jpg"/>
                <div class="main-description">
                    <h1>Some Kind Of nigato Title that would fit this blog</h1>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
                        sed do eiusmod tempor incididunt ut labore et dolore 
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
                        sed do eiusmod tempor incididunt ut labore et dolore Lorem 
                        ipsum dolor sit amet, consectetur adipiscing elit, sed do 
                        eiusmod tempor incididunt ut labore et dolore Lorem ipsum 
                        dolor sit amet, consectetur adipiscing elit, sed do eiusmod 
                        tempor incididunt ut labore et dolore </p>
                </div>
            </a>
            <br><br>
            <div class="two-items">
                <a href="#" class="item1 item">
                    <img class="small-image" src="https://i.pinimg.com/originals/9a/7c/fb/9a7cfb72bee5b42e2daa8ae46cff241a.jpg"/>
                    <div class="item-description">
                        <h1>Some Kind Of nigato Title that would fit this blog</h1>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
                        sed do eiusmod tempor incididunt ut labore et dolore 
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, </p>
                    </div>
                </a>
                <a href="#" class="item2 item">
                    <img class="small-image" src="https://i.pinimg.com/originals/9a/7c/fb/9a7cfb72bee5b42e2daa8ae46cff241a.jpg"/>
                    <div class="item-description">
                        <h1>Some Kind Of nigato Title that would fit this blog</h1>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
                        sed do eiusmod tempor incididunt ut labore et dolore 
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, </p>
                    </div>
                </a>
            </div>
        </div>
        <br><br>
        <h1><?= Lang::translate('Blogs'); ?></h1>
        <br><br>
        <div class="blog-archive-wrapper">
            <?php foreach ($blogs as $blog): ?>
                <div class="blog-card-wrapper">
                    <a href="<?= \App\Helper\Url::getUrl('/blog/page?id=' . $blog->getId()) ?>" class="blog-card">
                        <?= $blogImages[$blog->getId()]->toHtml() ?>
                        <div class="info-section">
                            <div class="blog-title"> <?= $blog->getTitle() ?> </div>
                            <div class="brief"> <?= $blog->getDescription() ?> </div>
                        </div>
                    </a>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <div id="footer"></div>
</body>

</html>