<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <title>Document</title>
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" type="text/javascript"></script>
    <script>
        $(function () {
            $("#footer").load("/templates/componenetns/footer.html");
        });
    </script>
</head>

<body>

<?php
    use Diversen\Lang;
?>
    <style>
        .contact-wrapper {
            margin-top: 50px;
            width: 100%;
            min-height: 84vh;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .contact-wrapper .section-title h1{
            border-bottom: 2px solid black;
        }

        .contact-wrapper p {
            text-align: center;
            width: 40%;
            margin-bottom: 40px;
        }

        .contact-wrapper .map-address {
            width: 100%;
            background-color: #3a3a3a;
            height: 60vh;
        }

        .address {
            width: 50%;
            height: 100%;
            float: left;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            color: white;
        }

        .address h3 {
            margin: 5px;
        }

        .map {
            width: 50%;
            height: 100%;
            float: right;
        }

        .map iframe {
            width: 100%;
            height: 100%;
        }



        /*low-res monitors*/
        @media screen and (max-width: 1368px) {}

        /*phone resolution*/
        @media screen and (max-width: 768px) {
            .contact-wrapper p {
                width: 90%;
            }

            .address {
                width: 100%;
                height: 50%;
                float: none;
            }

            .map {
                width: 100%;
                height: 50%;
                float: none;
            }

            .contact-wrapper .map-address {
                height: 100vh;
            }
        }
    </style>

    <div id="nav"> <?php \App\ViewModel\View::renderComponent('nav.phtml') ?> </div>
    <div class="contact-wrapper">
        <div class="section-title">
            <h1><?= Lang::translate('GET IN TOUCH'); ?></h1>
        </div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
            et dolore magna aliqua. Id velit ut tortor pretium. Molestie a iaculis at erat pellentesque
            adipiscing. Maecenas sed enim ut sem viverra aliquet. Mauris ultrices eros in cursus. Maecenas
            ultricies mi eget mauris pharetra et ultrices. In tellus integer feugiat scelerisque varius morbi.
            At elementum eu facilisis sed odio. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus
            semper</p>
        <div class="map-address">
            <div class="address">
                <h3><?= Lang::translate('Georgia, Tbilisi'); ?></h3>
                <h3><?= Lang::translate('I. Chavchavadze 39'); ?></h3>
                <h3>Info@ngslab.ge</h3>
                <h3>+995 595 64 84 49</h3>
            </div>
            <div class="map">
                <iframe
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d442.74126726279167!2d44.75572543792567!3d41.711965323852304!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40447339e8c37695%3A0x4af22ce353ca6fa1!2zMzkg4YOY4YOa4YOY4YOQIOGDreGDkOGDleGDreGDkOGDleGDkOGDq-GDmOGDoSDhg5Lhg5Dhg5vhg5bhg5jhg6Dhg5gsIOGDl-GDkeGDmOGDmuGDmOGDoeGDmA!5e0!3m2!1ska!2sge!4v1639225817547!5m2!1ska!2sge"
                    style="border:0;" allowfullscreen="" loading="lazy"></iframe>
            </div>
        </div>
    </div>
    <div id="footer"></div>
</body>

</html>