<?php
/** @var App\Model\Product[] $products */
/** @var App\Model\Image[] $productImages */
/** @var App\Model\Image[] $productLogos */

/** @var App\Model\User[] $productOwners */
/** @var App\Model\Image[] $productOwnerImages */

/** @var App\Model\Project[] $projects */
?>

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1" />
  <title>NGSLab</title>
  <link rel="stylesheet" href="/static/css/style.css" />
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" />
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" type="text/javascript"></script>
  <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />
  <script>
    $(function () {
      $("#footer").load("/templates/componenetns/footer.html");
    });
  </script>
</head>

<body>
  <style>
    #landing-component {
      width: 100%;
      height: 100%;
      display: flex;
      justify-content: center;
    }

    #product-owners-component {
      width: 100%;
      height: 100%;
    }


    #our-projects-component {
      width: 100%;
      height: 100%;
      overflow-y: scroll;
    }

    #product-owners-component::-webkit-scrollbar,
    #our-projects-component::-webkit-scrollbar {
      width: 0px;
    }


    .snapping-parent {
      scroll-snap-type: y mandatory;
      scroll-behavior: smooth;
      overflow-y: scroll;
      height: 93vh;
    }

    .snap-child {
      scroll-snap-align: center;
      scroll-behavior: smooth;
    }

    .swiper-main-wrapper {
      width: 90%;
      height: auto;
      min-height: 100%;
      display: flex;
      align-items: center;
      justify-content: space-between;
      flex-direction: column;
    }

    .swiper {
      width: 100%;
      height: 100%;
    }

    .swiper-slide {
      text-align: center;
      font-size: 18px;

      /* Center slide text vertically */
      display: -webkit-box;
      display: -ms-flexbox;
      display: -webkit-flex;
      display: flex;
      -webkit-box-pack: center;
      -ms-flex-pack: center;
      -webkit-justify-content: center;
      justify-content: center;
      -webkit-box-align: center;
      -ms-flex-align: center;
      -webkit-align-items: center;
      align-items: center;
    }

    .swiper-slide img {
      display: block;
      width: 100%;
      height: 100%;
      object-fit: cover;
    }

    .swiper {
      width: 100%;
      height: 300px;
      margin-left: auto;
      margin-right: auto;
    }

    .swiper-slide {
      background-size: cover;
      background-position: center;
    }

    .mySwiper2 {
      width: 100%;
      height: 70%;
      margin-top: 30px;
    }

    .mySwiper {
      background-color: #ebebeb;
      width: 80%;
      height: 100px;
      box-sizing: border-box;
      border-radius: 60px;
      padding-left: 100px;
      padding-right: 100px;
      margin-bottom: 20px;
    }

    .mySwiper .swiper-slide {
      width: 25%;
      height: 100%;
      cursor: pointer;
      transition: all 0.2s linear;
      border-radius: 40px;
    }

    .mySwiper .swiper-slide:hover {
      background-color: #cfcdcd;
    }


    .mySwiper .swiper-slide img {
      object-fit: contain;
      width: 80%;
      border-radius: 60px;
    }

    .mySwiper .swiper-slide-thumb-active {
      background-color: white;
      border-radius: 12vh;
    }

    .swiper-slide img {
      display: block;
      width: 100%;
      height: 100%;
      object-fit: cover;
    }

    .product-showcase-wrapper {
      width: 100%;
      height: 100%;
      display: flex;
      align-items: center;
      justify-content: space-around;
    }

    .product-image {
      width: 55%;
      height: 100%;
      display: flex;
      justify-content: center;
    }

    .product-image img {
      height: 100%;
      object-fit: contain;
    }

    .product-information {
      width: 40%;
      height: 100%;
      display: flex;
      flex-direction: column;
      justify-content: space-evenly;
    }

    .product-logo {
      width: 100%;
      max-height: 20%;
    }

    .product-logo img {
      width: 100%;
      object-fit: contain;
    }

    .product-slogan {
      width: 100%;
    }

    .product-description {
      width: 100%;
    }

    .product-description p {
      font-size: 1.1rem;
      padding: 15px;
      text-align: left;
    }

    .product-redirect-button a {
      float: right;
      text-decoration: none;
      color: #23af4d;
    }

    @media screen and (max-width: 768px) and (max-height: 875px) {
      .product-description p{
        font-size: 0.8em;
      }
    }

    /*phone resolution*/
    @media screen and (max-width: 768px) {
      
      .swiper-main-wrapper {
        height: 100vh;
      }

      .mySwiper {
        display: none;
      }

      .mySwiper2 {
        height: auto;
        margin-top:0;
      }

      .product-logo {
        width: auto;
        height: 10%;
      }

      .product-slogan h1 {
        font-size: 1.5em;
      }

      .product-image {
        display: none;
      }

      .product-information {
        width: 100%;
        justify-content: space-evenly;
      }
      .product-description p{
        text-align:justify;
      }
    }
  </style>

  <div id="nav"> <?php \App\ViewModel\View::renderComponent('nav.phtml') ?> </div>
  <div class="snapping-parent" id="snapping-parent">
    <div id="landing-component" class="snap-child">
      <div class="swiper-main-wrapper">
        <div class="swiper mySwiper2">
          <div class="swiper-wrapper">
              <?php foreach($products as $product): ?>
                <?php $image = $productImages[$product->getId()] ?? new \App\Model\Image() ?>
                <?php $logo = $productLogos[$product->getId()] ?? new \App\Model\Image() ?>
                <div class="swiper-slide">
                  <div class="product-showcase-wrapper">
                      <?php \App\ViewModel\View::renderComponent('landing-component-item.phtml', compact('product', 'image', 'logo')); ?>
                  </div>
                </div>
              <?php endforeach; ?>
          </div>
          <div class="swiper-pagination"></div>
        </div>

        <div thumbsSlider="" class="swiper mySwiper">
          <div class="swiper-wrapper">
            <?php foreach($products as $product): ?>
                <div class="swiper-slide thumbnailSlider">
                    <?= $productLogos[$product->getId()]->toHtml() ?>
                </div>
            <?php endforeach; ?>
          </div>
        </div>
      </div>

      <!-- Swiper JS -->
      <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

      <!-- Initialize Swiper -->
      <script>
        var swiper = new Swiper(".mySwiper", {
          spaceBetween: 10,
          slidesPerView: (document.querySelectorAll(".thumbnailSlider").length),
          freeMode: true,
          watchSlidesProgress: true,
          pagination: {
            el: ".swiper-pagination",
            clickable: true,
          },
        });
        var swiper2 = new Swiper(".mySwiper2", {
          spaceBetween: 10,
          noSwiping: true,
          navigation: {
            nextEl: ".swiper-button-next",
            prevEl: ".swiper-button-prev",
          },
          thumbs: {
            swiper: swiper,
          },
        });
      </script>
    </div>
    <br><br>
    <div id="product-owners-component" class="snap-child">
        <?php \App\ViewModel\View::renderComponent('product-owners-component.phtml',
            compact('productOwners', 'productOwnerImages')); ?>
    </div>
    <div id="our-projects-component" class="snap-child">
        <?php \App\ViewModel\View::renderComponent('our-projects-component.phtml',compact('projects')); ?>
    </div>
    <div id="footer" class="snap-child"></div>
  </div>
  <script src="/static/js/scroll-controller.js"></script>
</body>

</html>