<?php
/** @var \App\Model\User $user */
/** @var array $products */
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <title>Document</title>
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" type="text/javascript"></script>
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />
    <script>
        $(function () {
            $("#nav").load("/templates/componenetns/nav.html");
            $("#footer").load("/templates/componenetns/footer.html");
        });
    </script>
</head>

<body>
    <style>
        .product-owner-page-wrapper {
            width: 100%;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: space-evenly;
        }

        .product-owner-page-wrapper .profile-picture img {
            width: 300px;
            height: 300px;
            border-radius: 100%;
        }

        .social-icons-product-owner ul li a i {
            color: white;
            -webkit-transition: all 0.2s ease-in;
            -moz-transition: all 0.2s ease-in;
            -o-transition: all 0.2s ease-in;
            -ms-transition: all 0.2s ease-in;
            transition: all 0.2s ease-in;


        }

        .social-icons-product-owner ul li a i:hover {
            color: grey;
        }

        .social-icons-product-owner ul {
            display: flex;
            align-items: center;
        }

        .social-icons-product-owner h1 {
            margin: 40px 0;
        }

        .social-icons-product-owner ul {
            list-style: none;
            margin: 0;
            padding: 0;
        }

        .social-icons-product-owner ul li a {
            display: flex;
            justify-content: center;
            align-items: center;
            font-size: 2em;
            margin: 0 15px;
            text-decoration: none;
            background-color: #5d5d5d;
            width: 50px;
            height: 50px;
            border-radius: 100%;
        }

        .product-owner-page-wrapper .owner-bio {
            width: 70%;
            text-align: center;
        }

        .product-owner-page-wrapper .products {
            display: flex;
            flex-wrap: wrap;
            flex-direction: row;
            justify-content: center;
            width: 100%;
            height: auto;

        }

        .product-card-component {
            width: 100%;
            height: 100%;
            border-radius: 30px;
            background-color: black;
            display: flex;
            flex-direction: column;
        }

        .product-owner-page-wrapper .projects {
            width: 100%;
        }

        .our-projects-component-wrapper .project-listing ul {
            list-style-type: circle;
        }

        .our-projects-component-wrapper .project-listing ul a {
            text-decoration: none;
            color: black;
        }


        .our-projects-component-wrapper .project-listing .our-project-listing-item {
            width: 85%;
            font-size: 1.5em;
        }

        .our-projects-component-wrapper .project-listing .our-project-listing-item .project-description {
            font-size: 0.8em;
            margin: 0;
        }

        .product-card-component{
            color: white;
            display: flex;
            justify-content: space-evenly;
            align-items: center;
            width: 100%;
            height: 100%;
            background-color: #ebebeb;
        }

        .swiper {
            width: 70%;
            height: 100%;
        }

        .swiper-slide {
            max-width: 95vw;
            max-height: 95vw;
            width: 410px;
            height: 410px;
            text-align: center;
            font-size: 18px;
            background: #fff;

            /* Center slide text vertically */
            display: -webkit-box;
            display: -ms-flexbox;
            display: -webkit-flex;
            display: flex;
            -webkit-box-pack: center;
            -ms-flex-pack: center;
            -webkit-justify-content: center;
            justify-content: center;
            -webkit-box-align: center;
            -ms-flex-align: center;
            -webkit-align-items: center;
            align-items: center;
        }

        @media screen and (max-width: 768px) {


            .product-owner-page-wrapper .owner-bio {
                width: 90%;
            }
        }
    </style>
    <div id="nav"></div>
    <div id="product-owner-component">

        <div class="product-owner-page-wrapper">

            <div class="profile-picture">
                <img src="<?= $user->getImage() ?>">
            </div>

            <div class="profile-name">
                <h1><?= $user->getName() ?></h1>
            </div>

            <div class="socials">
                <div class="social-icons-product-owner">
                    <ul>
                        <li><a href="#"><i class=" icon-facebook"></i></a></li>
                        <li><a href="#"><i class=" icon-linkedin"></i></a></li>
                        <li><a href="#"><i class="icon-instagram"></i></a></li>

                    </ul>
                </div>
            </div>

            <div class="owner-bio">
                <p> <?= $user->getDescription() ?></p>
            </div>

            <div class="products">
                <div class="swiper mySwiper">
                    <div class="swiper-wrapper">
                        <?php /** @var \App\Model\Product $product */ ?>
                        <?php foreach ($products as $product): ?>
                        <div class="swiper-slide">
                            <div class="product-card-component">
                                <a href="/product/page?id=<?= $product->getId() ?>" class="product-card-component">
                                    <div class="product-name"> <?= $product->getName() ?> </div>
                                    <div class="slogan"><?= $product->getShortDescription() ?></div>
                                    <div class="description"><p><?= $product->getDescription() ?></p></div>
                                    <img src="<?= $product->getImage() ?>" alt="">
                                </a>
                            </div>
                        </div>
                        <?php endforeach; ?>
                    </div>
                    <br>
                    <br>
                    <br>
                    <div class="swiper-pagination"></div>
                </div>
            </div>
            <!-- Swiper JS -->

            <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

            <!-- Initialize Swiper -->
            <script>
                var swiper = new Swiper(".mySwiper", {
                    slidesPerView: 1,
                    spaceBetween: 30,
                    pagination: {
                        el: ".swiper-pagination",
                        clickable: true,
                    },
                    breakpoints: {
                        // when window width is <= 499px
                        1368: {
                        slidesPerView:2,
                        },
                    }
                });
            </script>

            <script>
                $(function () {
                    $("#our-project-listing-item-component1").load("/templates/componenetns/our-project-listing-item-component.html");
                    $("#our-project-listing-item-component2").load("/templates/componenetns/our-project-listing-item-component.html");
                });
            </script>

            <div class="projects">
                <h1 style="margin-left: 50px;">Projects</h1>
                <div class="our-projects-component-wrapper">
                    <div style="margin-left: 50px; margin-right: 50px;" class="project-listing">
                        <ul>
                            <div id="our-project-listing-item-component1"></div>
                            <div id="our-project-listing-item-component2"></div>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div id="footer"></div>
</body>

</html>