<?php
/** @var \App\Model\Product $product */
?>

<!DOCTYPE html>
<html lang="en">
<style>
    .product-page-component-wrapper {
        width: 100%;
    }

    .product-page-component-wrapper .section1 {
        width: calc(100% - 60px);
        min-height: 86vh;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        margin: 50px;
    }

    .product-page-component-wrapper .section2 {
        width: calc(100% - 60px);
        min-height: 86vh;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        margin: 30px;
    }

    .product-page-component-wrapper .section3 {
        width: calc(100% - 60px);
        min-height: 86vh;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        margin: 50px;
    }

    .product-showcase-wrapper {
        width: 85%;
        height: 60%;
        display: flex;
        justify-content: space-between;
        flex-wrap: wrap;
    }

    .product-page-component-wrapper .section2 {
        width: 100%;
        min-height: 86vh;
    }

    .product-page-component-wrapper .section3 {
        width: 100%;
        min-height: 86vh;
    }

    .product-image {
        width: 45%;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }

    .product-image img {
        width: 100%;
        object-fit: contain;
    }

    .product-information {
        width: 45%;
        height: 100%;
        display: flex;
        flex-direction: column;
        justify-content: space-evenly;
    }

    .product-logo {
        width: 100%;
    }

    .product-logo img {
        width: 100%;
    }

    .product-slogan {
        width: 100%;
    }

    .product-slogan h1 {
        padding: 15px;
    }

    .product-desctiption {
        width: 100%;
    }

    .product-desctiption p {
        font-size: 1.3em;
    }

    .product-pro-list {
        width: 45%;
        height: 100%;
        display: flex;
        flex-direction: column;
        justify-content: space-evenly;
    }

    .section2 .product-showcase-wrapper .product-image {
        height: 100%;
        width: auto;
    }

    .section2 .product-showcase-wrapper .product-image img {
        height: 100%;
        width: auto;
    }

    @media screen and (max-width: 1368px) {
        .product-showcase-wrapper {
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        .product-image {
            width: 100%;
            height: 100%;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
        .project-componenet-wrapper .description {
            width: 100%;
        }
        .product-image img {
            width: 85%;
            object-fit: contain;
        }
        .product-information {
            width: 85%;
            display: flex;
            flex-direction: column;
            justify-content: space-evenly;
        }
        .section2 .product-showcase-wrapper .product-pro-list {
            align-items: flex-start;
            width: 100%;
        }
    }
</style>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <title>Document</title>
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" type="text/javascript"></script>
    <script>
        $(function () {
            $("#nav").load("/templates/componenetns/nav.html");
            $("#footer").load("/templates/componenetns/footer.html");
        });
    </script>
</head>

<body>
    <div id="nav"></div>
    <div id="product-page-componenet">

        <div class="product-page-component-wrapper">
            <div class="section1">
                <div class="product-showcase-wrapper">
                    <div class="product-information">
                        <div class="product-logo">
                            <img src="https://www.scrumdesk.com/wp-content/uploads/jira-logo-gradient-blue@2x-1.png" />
                        </div>
                        <div class="product-slogan">
                            <h1> <?= $product->getShortDescription() ?> </h1>
                        </div>
                        <div class="product-desctiption">
                            <p>
                                <?= $product->getDescription() ?>
                            </p>
                        </div>
                    </div>
                    <div class="product-image">
                        <img src="https://clearhub.tech/wp-content/uploads/2018/08/AppLogo_Jira.png" />
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="footer"></div>
</body>

</html>