<?php
/** @var \App\Model\Product $product */
/** @var \App\Model\Image $image */
/** @var \App\Model\Image $gif */
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <meta name="title" property="og:title" content="<?= $product->getMetaTitle() ?>">
    <meta name="keywords" content="<?= $product->getMetaKeyword() ?>">
    <meta name="description" property="og:description" content="<?= $product->getMetaDescription() ?>">
    <meta name="thumbnail" property="og:image" content="<?= $image->getValue() ?>">
    <title><?= $product->getName() ?> | NGSLab</title>
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" type="text/javascript"></script>
    <script>
        $(function () {
            $("#footer").load("/templates/componenetns/footer.html");
        });
    </script>
</head>

<body>
    <div id="nav"> <?php \App\ViewModel\View::renderComponent('nav.phtml') ?> </div>
    <?= $product->getPageHtml() ?>
    <div id="footer"></div>
</body>

</html>