<?php
/** @var App\Model\Project $project */
/** @var App\Model\Image $image */
/** @var App\Model\Image $logo */
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <meta name="title" property="og:title" content="<?= $project->getMetaTitle() ?>">
    <meta name="keywords" content="<?= $project->getMetaKeyword() ?>">
    <meta name="description" property="og:description" content="<?= $project->getMetaDescription() ?>">
    <meta name="thumbnail" property="og:image" content="<?= $image->getValue() ?>">
    <title><?= $project->getName() ?> | NGSLab</title>
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" type="text/javascript"></script>
    <script>
        $(function () {
            $("#footer").load("/templates/componenetns/footer.html");
        });
    </script>
    <style>
        #Carousel {
            height: 100%;
            display: block;
            width: 100%;
            float: left;
            margin: 0;
            position: relative;
            background-position: center;
            /* Center the image */
            background-repeat: no-repeat;
            /* Do not repeat the image */
            background-size: contain;
            /* Resize the background image to cover the entire container */
        }

        .carousel-inner-wrapper {
            height: 100%;
            width: 100%;
            background-position: center;
            /* Center the image */
            background-repeat: no-repeat;
            /* Do not repeat the image */
            background-size: cover;
            border-radius: 25px;
        }

        .Button-display-left {
            position: absolute;
            top: 50%;
            left: 0%;
            transform: translate(0%, -50%);
            border-right: 10px solid;
        }

        .Button-display-right {
            position: absolute;
            top: 50%;
            right: 0%;
            transform: translate(0%, -50%);
            border-left: 10px solid;
        }

        .Button:hover {
            background-color: rgba(46, 46, 46, 0.3);
        }

        .Button {
            background-color: rgba(46, 46, 46, 0.1);
            color: #fff;
            border: none;
            padding: 5vh 20px;
            text-align: center;
            text-decoration: none;
            font-size: 2.5vw;
            overflow: hidden;
            text-indent: 0px;
            text-shadow: none;
            transition: 0.2s;
            border-color: white;
        }


    </style>
</head>

<body>
    <div id="nav"> <?php \App\ViewModel\View::renderComponent('nav.phtml') ?> </div>
    <div id="project-componenent">
        <?php \App\ViewModel\View::renderComponent('project-component.phtml',
            compact('project', 'image', 'logo')); ?>
    </div>
    <div id="footer"></div>
    <script src="/static/js/projectCarouselController.js"></script>
</body>

</html>