<?php
    use Diversen\Lang;
/** @var App\Model\Project[] $projects */
/** @var App\Model\Image[] $projectImages */
/** @var App\Model\Image[] $projectLogos */
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <title>Document</title>
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" type="text/javascript"></script>
    <script>
        $(function() {
            $("#footer").load("/templates/componenetns/footer.html");
        });
    </script>
</head>

<body>
    <style>
        .our-projects-wrapper {
            margin-top: 50px;
            width: 100%;
            min-height: 84vh;
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        
        .projects-gallery {
            position: relative;
            margin-top: 50px;
            text-align: center;
            justify-content: center;
            display: flex;
            flex-wrap: wrap;
        }
        
        .our-projects-wrapper .section-title h1 {
            border-bottom: 2px solid black;
            margin: 0;
        }
        
        .project-gallery-item-wrapper {
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
            width: 480px;
            height: 270px;
            background-color: black;
            display: block;
            margin: 30px;
            border-radius: 50px;
            color: white;
        }
        
        .color-overlay {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            width: 100%;
            height: 100%;
            border-radius: 50px;
            background-color: rgba(0, 0, 0, 0.253);
        }
        /*low-res monitors*/
        
        @media screen and (max-width: 1368px) {}
        /*phone resolution*/
        
        @media screen and (max-width: 768px) {
            .project-gallery-item-wrapper {
                width: 90vw;
                height: 50vw;
                background-color: black;
            }
        }
    </style>

    <div id="nav"> <?php \App\ViewModel\View::renderComponent('nav.phtml') ?> </div>
    <div class="our-projects-wrapper">
        <div class="section-title">
            <h1><?= Lang::translate('OUR PROJECTS'); ?></h1>
        </div>

        <div class="project-gallery-wrapper">
            <div class="projects-gallery">
                <?php foreach ($projects as $project): ?>
                    <?php $projectLink = \App\Helper\Url::getUrl('/project?id=' . $project->getId()) ?>
                    <div>
                        <a href="<?= $projectLink ?>" class="project-gallery-item-wrapper"
                           style="background-image:url(<?= $projectLogos[$project->getId()]->getValue() ?>);">
                            <div class="color-overlay">
                                <h2> <?= $project->getName() ?> </h2>
                            </div>
                        </a>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    <div id="footer"></div>
</body>

</html>