<?php
use App\Config\Config;
?>

<style>
    .errors {
        display: flex;
        flex-direction: column;
    }

    .error-wrapper {
        background: #f79a9a;
        padding: 0 10px 10px 15px;
        margin-top: 10px;
        font-family: initial;
    }

    .error-wrapper h4 {
        margin: 10px 0 0 15px;
    }

    .error-wrapper ol {
        line-height: 21px;
        margin-top: 10px;
    }
</style>

<?php if (\App\Helper\AdminSession::getErrorLog()): ?>
    <div class="errors">
        <?php /** @var \Exception $error */ ?>
        <?php foreach (\App\Helper\AdminSession::getErrorLog() as $error): ?>
            <div class="error-wrapper">
                <?php $prev = $error->getPrevious() ? $error->getPrevious()->getMessage() : '' ?>
                <h4>&#10060; <?= $error->getMessage() . $prev ?></h4>
                <?php if (\App\Helper\AdminSession::isLoggedIn()): ?>
                    <?php if (\App\Helper\AdminSession::hasPermission(\App\Controller\Admin\AbstractAdminAction::PERMISSION_DEVELOPER)
                        && Config::get('admin/settings/show_trace') == '1'): ?>
                    <?php $traceList = explode("\n", $error->getTraceAsString()); ?>
                    <ol>
                        <?php foreach ($traceList as $trace): ?>
                            <li><?= strstr($trace, ' ') ?> </li>
                        <?php endforeach; ?>
                    </ol>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>
    <?php \App\Helper\AdminSession::clearErrorLog(); ?>
<?php endif; ?>
