<?php
    use Diversen\Lang;
/** @var App\Model\Product $product */
/** @var App\Model\Image $image */
/** @var App\Model\Image $logo */
?>

<div class="product-image">
    <?= $image->toHtml() ?>
</div>
<div class="product-information">
  <div class="product-logo">
      <?= $logo->toHtml() ?>
  </div>
  <div class="product-slogan">
    <h1> <?= $product->getName() ?> </h1>
  </div>
  <div class="product-description">
    <p>
        <?= $product->getShortDescription() ?>
    </p>
    <div class="product-redirect-button">
      <a href="<?= \App\Helper\Url::getUrl('/product/page?id=' . $product->getId()) ?> "><?= Lang::translate('READ MORE'); ?></a>
    </div>
  </div>
</div>
