<?php
    use Diversen\Lang;
?>

<style>
    /*Navigation WideScreen*/
    .nav-placeholder {
        height: 6vh;
        width: 100%;
    }

    nav {
        height: 6vh;
        min-height: 45px;
        transition: all 0.5s ease;
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        z-index: 101;
        background-color: #fff;

    }

    .hamburger {
        display: none;
    }

    .logo-container {
        display: none;
        height: 100%;
        margin-right: 0;
    }

    .nav-logo {
        margin-left: 40px;
        height: 100%;
        display: inline-block;
    }

    .logo-container {
        display: inline-block;
    }

    .inner-logo-container {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        height: 100%;
    }

    .inner-logo-container img {
        height: 85%;
    }

    .nav-links {
        display: flex;
        list-style: none;
        width: auto;
        height: 100%;
        width: 70%;
        justify-content: space-around;
        align-items: center;
        margin: 0;
        float: right;
        background-color: white;
        stroke-width: 1px;
    }

    .nav-links li a {
        color: black;
        text-decoration: none;
        font-size: 1.1rem;
        transition: width 2s, height 2s, transform 0.5s;
        font-weight: 900;
        transition: all 0.2s linear;
    }

    .nav-links li {
        text-align: center;
        margin-right: 10px;
        transition: width 2s, height 2s, transform 0.5s;
    }

    .scrolling-active {
        height: 7vh;
    }

    .scrolling-active .nav-links {
        background-color: rgba(0, 0, 0, 0.0);
    }

    .scrolling-active li a {
        color: #313131;

    }

    @media screen and (max-width: 768px) {
        .logo-container {
            width: 100%;
            text-align: center;
        }

        .nav-logo {
            margin: 0;
        }

        .inner-logo-container {
            flex-direction: row;
            align-items: center;
        }

        .nav-links {
            position: absolute;
            top: -2px;
            background-color: white;
            height: 70vh;
            width: 100%;
            flex-direction: column;
            clip-path: circle(7vh at 100% -10%);
            -webkit-clip-path: circle(7vh at 100% -10%);
            transition: all 0.7s ease;
            pointer-events: none;
            margin: 0;
            padding: 0;
            padding-top:50px;
        }

        .nav-links.open {
            clip-path: circle(300vh at 100% -10%);
            -webkit-clip-path: circle(300vh at 100% -10%);
            pointer-events: all;
            background-color: white;
        }

        .nav-links li {
            opacity: 0;
        }

        .nav-links li a {
            font-size: 20px;
            color: black;
        }

        .nav-links li:nth-child(1) {
            transition: all 0.5s ease 0.1s;
        }

        .nav-links li:nth-child(2) {
            transition: all 0.5s ease 0.15s;
        }

        .nav-links li:nth-child(3) {
            transition: all 0.5s ease 0.2s;
        }

        .nav-links li:nth-child(4) {
            transition: all 0.5s ease 0.25s;
        }

        .nav-links li:nth-child(5) {
            transition: all 0.5s ease 0.3s;
        }

        li.fade {
            opacity: 1;
        }

        .scrolling-active li a {
            color: black;
        }

        .scrolling-active {
            background-color: white;
        }

        .hamburger {
            display: block;
            position: absolute;
            cursor: pointer;
            right: 5%;
            top: 50%;
            transform: translate(-5%, -50%);
            z-index: 2;
        }

        .trigger {
            position: absolute;
            z-index: 2;
            left: 50%;
            top: 50%;
            transform: translateX(-50%) translateY(-50%);
        }

        .bars {
            height: 8vh;
            cursor: pointer;
        }

        .bars .line {
            fill: none;
            stroke: black;
            stroke-width: 4;
            stroke-linecap: square;
            transition: stroke-dasharray 400ms, stroke-dashoffset 400ms;
        }

        .scrolling-active .bars .line {
            stroke: black;
        }

        .inNavigation .bars .line {
            stroke: black;
        }

        .bars .line.top {
            stroke-dasharray: 40 172;
        }

        .bars .line.middle {
            stroke-dasharray: 40 111;
        }

        .bars .line.bottom {
            stroke-dasharray: 40 172;
        }

        .bars.active .top {
            stroke-dashoffset: -132px;
        }

        .bars.active .middle {
            stroke-dashoffset: -71px;
        }

        .bars.active .bottom {
            stroke-dashoffset: -132px;
        }

    }
</style>

<nav>
    <div class="hamburger">
        <div class="trigger">
            <svg class="bars" viewBox="0 0 100 100" onclick="this.classList.toggle('active')">
                <path class="line top"
                    d="m 30,33 h 40 c 13.100415,0 14.380204,31.80258 6.899646,33.421777 -24.612039,5.327373 9.016154,-52.337577 -12.75751,-30.563913 l -28.284272,28.284272">
                </path>
                <path class="line middle"
                    d="m 70,50 c 0,0 -32.213436,0 -40,0 -7.786564,0 -6.428571,-4.640244 -6.428571,-8.571429 0,-5.895471 6.073743,-11.783399 12.286435,-5.570707 6.212692,6.212692 28.284272,28.284272 28.284272,28.284272">
                </path>
                <path class="line bottom"
                    d="m 69.575405,67.073826 h -40 c -13.100415,0 -14.380204,-31.80258 -6.899646,-33.421777 24.612039,-5.327373 -9.016154,52.337577 12.75751,30.563913 l 28.284272,-28.284272">
                </path>
            </svg>
        </div>
    </div>

    <!---logo goes here-->

    <a href="<?= \App\Helper\Url::getUrl('/') ?>"><div class="logo-container">
        <div class="inner-logo-container">
            <img class="nav-logo" src="/static/images/ngs.png   ">
        </div>
    </div></a>


    <ul class="nav-links">
        <li><a id="owners-nav" href="<?= \App\Helper\Url::getUrl('/#product-owners-component') ?>"><span><?= Lang::translate('PRODUCT OWNERS'); ?></span></a></li>
        <li><a id="projects-nav" href="<?= \App\Helper\Url::getUrl('/project/listing') ?>"><span><?= Lang::translate('PORTFOLIO'); ?></span></a></li>
        <li><a id="catalog-nav" href="<?= \App\Helper\Url::getUrl('/product/catalog') ?>"><span><?= Lang::translate('CATALOG'); ?></span></a></li>
        <li><a id="blog-nav" href="<?= \App\Helper\Url::getUrl('/blog') ?>"><span><?= Lang::translate('BLOG'); ?></span></a></li>
        <li><a id="about-nav" href="<?= \App\Helper\Url::getUrl('/about') ?>"><span><?= Lang::translate('ABOUT US'); ?></span></a></li>
        <li><a id="contact-nav" href="<?= \App\Helper\Url::getUrl('/contact') ?>"><span><?= Lang::translate('CONTACT'); ?></span></a></li>
        <li><a style="cursor: hand;" id="language-button" onclick="ChangeLanguage()" href="javascript:void(0)"><span style="cursor: hand;">currentLanguage</span></a></li>
    </ul>
</nav>
<div id="nav-placeholder" class="nav-placeholder"></div>
<script src="/static/js/navigation.js"></script>
<script src="/static/js/urlHandler.js"></script>