<?php
/** @var App\Model\Project[] $projects */
?>

<style>
    .our-projects-component-wrapper {
        width: 100%;
        min-height: 93vh;
        background-color: #3a3a3a;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: space-between;
    }
    
    .our-projects-component-wrapper .section-title h1 {
        font-size: 45px;
        padding: 5px;
        margin: 10px;
        color: white;
        border-bottom: 2px solid white;
    }
    
    .our-projects-component-wrapper .project-listing {
        color: white;
        width: 85%;
        height: 75%;
    }
    
    .our-projects-component-wrapper .project-listing ul {
        padding:0;  
        list-style-type: circle;
    }
    
    .our-projects-component-wrapper .project-listing ul a {
        text-decoration: none;
        color: white;
    }
    
    .our-projects-component-wrapper .project-listing .our-project-listing-item {
        width: 85%;
        font-size: 2em;
        margin: 50px;
    }
    
    .our-projects-component-wrapper .project-listing .our-project-listing-item .project-description {
        font-size: 0.6em;
        margin: 0;
    }
    
    .our-project-listing-item h1 {
        margin: 0;
    }
    
    .our-project-listing-item p {
        margin: 0;
    }
    
    .project-gallery-item-wrapper {}
    
    .our-projects-component-wrapper .read-more-button {
        width: 210px;
        height: 70px;
        font-size: 1.2em;
        background-color: #23af4d;
        color: white;
        text-align: center;
        line-height: 70px;
        border-radius: 35px;
        margin-bottom: 20px;
    }
    
    .our-projects-component-wrapper .read-more-button a {
        text-decoration: none;
        color: black;
    }
    
    @media screen and (max-width: 1368px) {}
    /*phone resolution*/
    
    @media screen and (max-width: 768px) {
        .our-projects-component-wrapper .project-listing {
            color: white;
            width: 95%;
            height: 75%;
        }
        .our-projects-component-wrapper {
            min-width: 0;
            width: 100%;
        }
        .our-projects-component-wrapper .project-listing .our-project-listing-item {
            width: 85%;
            font-size: 1.5em;
            margin: 35px;
        }
    }
</style>

<div class="our-projects-component-wrapper">
    <div class="section-title">
        <h1>Our Projects</h1>
    </div>
    <div class="project-listing">
        <ul>
            <?php foreach ($projects as $project): ?>
                <?php $projectLink = '/project?id=' . $project->getId() ?>
                <div>
                    <a href="<?= $projectLink ?>">
                        <li class="our-project-listing-item">
                            <p class="project-title"> <?= $project->getName(); ?> </p>
                            <p class="project-description"> <?= $project->getShortDescription(); ?> </p>
                        </li>
                    </a>
                </div>
            <?php endforeach; ?>
        </ul>
    </div>
    <div class="read-more-button">
        <a href="/project/listing">READ MORE</a>
    </div>
</div>