<?php
/** @var App\Model\User[] $productOwners */
/** @var App\Model\Image[] $productOwnerImages */
?>


<style>
    .product-owners-component-wrapper {
        width: 100%;
        height: 100%;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: space-evenly;
        text-align: center;
    }

    .product-owners-wrapper {
        width: 100%;
        display: flex;
        justify-content: space-around;
        align-items: center;
        flex-wrap: wrap;
    }

    .product-owner-wrapper {
        position: relative;
        background-color: #3a3a3a;
        border-radius: 70px;
        width: 50vh;
        height: 50vh;
    }

    .product-owner-wrapper .default-card {
        position: absolute;
        width: 100%;
        height: 100%;
        border-radius: inherit;
        z-index: 1;
        background-position: center;
        background-repeat: no-repeat;
        background-size: contain;
        color: white;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: flex-end;
    }

    /* .product-owner-wrapper .default-card:hover {
        visibility: hidden;
    } */

    .product-owner-card .hovered-card {
        position: absolute;
        width: 100%;
        height: 100%;
        border-radius: inherit;
        z-index: 0;
        display: flex;
        flex-direction: column;
        align-items: center;
        color: white;
        justify-content: space-around;
        font-size: 0.7em;
    }

    .product-owner-card .hovered-card p {
        width: 90%;
        font-size: 1.2em;
    }

    .product-owner-card .hovered-card img {
        border-radius: 100%;
        height: 15vh;
        width: 15vh;
    }

    .product-owner-card .hovered-card a {
        padding: 20px;
        border-radius: 20px;
        background-color: white;
        color: black;
        cursor: pointer;
    }

    .product-owner-wrapper h1 {
        position: relative;
        height: 30px;
        width: calc(100% - 60px);
        line-height: 30px;
        text-align: left;
        padding: 30px;
        background-color: #ebebeb;
        position: relative;
        border-radius: 70px 70px 0 0;
    }

    .product-owners-component-wrapper .section-title {
        text-align: center;
        border-bottom: 2px solid black;
    }

    .product-owners-component-wrapper p {
        font-size: 1.45em;
        width: 60%;
    }

    .product-owner-component {
        text-decoration: none;
        color: black;
    }

    .product-owner-component:hover~.product-owner-wrapper-hovered {
        display: block;
    }

    .active {
        display: block;
    }

    .hidden {
        display: none;
    }

    .mySwiper3 {
        width: 70%;
        height: 65%;
        display: flex;
        flex-direction: row;
        align-items: center;
    }

    .swiper-slide3 {
        width: 350px;
        height: 350px;
        text-align: center;
        font-size: 18px;
        background: #fff;

        /* Center slide text vertically */
        display: -webkit-box;
        display: -ms-flexbox;
        display: -webkit-flex;
        display: flex;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        -webkit-justify-content: center;
        justify-content: center;
        -webkit-box-align: center;
        -ms-flex-align: center;
        -webkit-align-items: center;
        align-items: center;
    }

    .owner-info-wrapper {
        height: 35%;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: space-around;
        text-align: center;
    }

    /*low-res monitors*/

    @media screen and (max-width: 1368px) {}

    /*phone resolution*/

    @media screen and (max-width: 768px) {
        .mySwiper3{
            width: 100%;
        }
        .product-owners-component-wrapper {
            width: 100%;
            min-width: 0;
            justify-content: space-between;
        }

        .product-owners-wrapper {
            width: 100%;
            display: flex;
            justify-content: space-around;
            align-items: center;
        }

        .product-owner-wrapper {
            width: 80vw;
            height: 80vw;
            min-width: 200px;
            min-height: 200px;
        }

        .owner-info-wrapper {
            font-size: 0.7em;
        }


        .product-owner-wrapper h1 {
            font-size: 1.5em;
            position: relative;
            height: 20px;
            width: calc(100% - 40px);
            line-height: 20px;
            text-align: left;
            padding: 20px;
            background-color: #ebebeb;
            position: relative;
            border-radius: 70px 70px 0 0;
        }

        .product-owners-component-wrapper p {
            width: 95%;
        }

        .product-owner-card .hovered-card p{
            font-size: 1em;
            /* display: none; */
        }
        .product-owner-card .hovered-card img {
        border-radius: 100%;
        height: 13vh;
        width: 13vh;
    }

    }
</style>


<div class="product-owners-component-wrapper">

    <div class="owner-info-wrapper">
        <div class="section-title">
            <h1>PRODUCT OWNERS</h1>
        </div>
        <p class="product-owners-description">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
            dolore Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
            et
            dolore Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
            et
            dolore Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
            et
            dolore
        </p>
    </div>

    <div class="swiper mySwiper3">
        <div style="align-items: center;" class="swiper-wrapper">
            <?php foreach ($productOwners as $productOwner): ?>
                <?php $productOwnerImage = $productOwnerImages[$productOwner->getId()] ?>
                <div class="swiper-slide swiper-slide3">
                    <div class="product-owner-card" id="product-owner1">
                        <div href="/product/owner?id=<?= $productOwner->getId() ?>" class="product-owner-component">
                            <div class="product-owner-wrapper">
                                <div class="default-card"
                                    style="background-image: url(<?= $productOwnerImage->getValue() ?>);">
                                    <h2><?= $productOwner->getName() ?></h2>
                                </div>
                                <div class="hovered-card">
                                    <h2><?= $productOwner->getName() ?></h2>
                                    <?= $productOwnerImage->toHtml() ?>
                                    <p class="description"> <?= $productOwner->getShortDescription() ?> </p>
                                    <a href="<?= \App\Helper\Url::getUrl('/product/owner?id=' . $productOwner->getId()) ?>">Read More</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <br>
        <div class="swiper-pagination"></div>
    </div>

    <script>
        var swiper = new Swiper(".mySwiper3", {
            slidesPerView: 1,
            spaceBetween: 30,
            centeredSlides: true,
            pagination: {
                el: ".swiper-pagination",
                clickable: true,
            },
            breakpoints: {
                // when window width is <= 499px
                1368: {
                    centeredSlides: false,
                    slidesPerView: (document.querySelectorAll(".swiper-slide3").length >=2 ? 2 : 1),
                },
            }
        });
    </script>

    <script src="/static/js/card-controler.js"></script>
</div>