<?php
/** @var App\Model\Project $project */
/** @var App\Model\Image $image */
/** @var App\Model\Image $logo */
?>

<style>
    .project-componenet-wrapper {
        width: 100vw;
        min-height: 87vh;
        height: auto;
        display: flex;
        justify-content: space-evenly;
    }
    
    .project-componenet-wrapper .description {
        height: 100%;
        width: 45%;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: space-evenly;
        padding: 50px;
    }
    
    .project-componenet-wrapper .description p {
        font-size: 1.5em;
    }
    
    .project-componenet-wrapper .description h1 {
        margin: 0;
    }
    
    .project-componenet-wrapper .image-carousel {
        height: 84vh;
        margin-top: 50px;
        width: 45vw;
        background-position: center;
        background-repeat: no-repeat;
        background-size: contain;
        display: block;
    }

    #Carousel {
            height: 100%;
            display: block;
            width: 100%;
            float: left;
            margin: 0;
            position: relative;
            background-position: center;
            /* Center the image */
            background-repeat: no-repeat;
            /* Do not repeat the image */
            background-size: contain;
            /* Resize the background image to cover the entire container */
        }

        .carousel-inner-wrapper {
            height: 100%;
            width: 100%;
            background-position: center;
            /* Center the image */
            background-repeat: no-repeat;
            /* Do not repeat the image */
            background-size: cover;
            border-radius: 25px;
        }

        .Button-display-left {
            position: absolute;
            top: 50%;
            left: 0%;
            transform: translate(0%, -50%);
            border-right: 10px solid;
        }

        .Button-display-right {
            position: absolute;
            top: 50%;
            right: 0%;
            transform: translate(0%, -50%);
            border-left: 10px solid;
        }

        .Button:hover {
            background-color: rgba(46, 46, 46, 0.3);
        }

        .Button {
            background-color: rgba(46, 46, 46, 0.1);
            color: #fff;
            border: none;
            padding: 5vh 20px;
            text-align: center;
            text-decoration: none;
            font-size: 2.5vw;
            overflow: hidden;
            text-indent: 0px;
            text-shadow: none;
            transition: 0.2s;
            border-color: white;
        }
    /*phone resolution*/
    
    @media screen and (max-width: 1368px) {
        .project-componenet-wrapper {
            flex-direction: column;
            align-items:center;
        }
        .project-componenet-wrapper .description {
            width: 85%;
            text-align:justify;
        }
        .project-componenet-wrapper .image-carousel {
            position: relative;
            height: 80vh;
            margin-top: 0;
            width: 85%;
        }
        .project-componenet-wrapper .image-carousel img{
            width:100%;
        }
    }
</style>

<div class="project-componenet-wrapper">
    <div class="description">
        <h1> <?= $project->getName() ?> </h1>
        <p> <?= $project->getDescription() ?></p>
    </div>
    <div class="image-carousel">
    <script>let imageArray = [ <?= $project->getSliderHtml() ?>];</script>

         <div id="Carousel">
            <div id="inner-carousel" class="carousel-inner-wrapper"></div>
            <button class="Button Button-display-left" onclick="plusDivs(-1)" style="display:inline-block">❮</button>
            <button class="Button Button-display-right" onclick="plusDivs(1)" style="display:inline-block">❯</button>
        </div>

    </div>
</div>
