<?php
/** @var App\Model\Blog $blog */
/** @var App\Model\Image $image */
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <title>Document</title>
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" type="text/javascript"></script>
    <script>
        $(function () {
            $("#footer").load("/templates/componenetns/footer.html");
        });
    </script>
    <?php $tinyApiKey = \App\Config\Config::get('tiny_mce/editor/api') ?>
    <script src="https://cdn.tiny.cloud/1/<?= $tinyApiKey ?>/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>
        tinymce.init({
            selector: '#blog_body',
            plugins: 'code image imagetools preview link anchor lists advlist fullscreen hr',
            toolbar: 'undo redo | numlist bullist hr link image anchor | preview code fullscreen',
            width: 850,
            height: 550,
        });
    </script>
</head>

<body>
<style>
    .about-wrapper {
        margin-top: 50px;
        width: 100%;
        min-height: 84vh;
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .about-wrapper .section-title h1 {
        border-bottom: 2px solid black;
    }

    .about-wrapper p {
        text-align: center;
        width: 40%;
        margin-bottom: 40px;
    }
    .team-member-wrapper{
        width: 100%;
        min-height: 60vh;
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        align-items: center;
        justify-content: space-evenly;
    }

    .box{
        margin: 15px;
        width: 300px;
        height: 300px;
        background-color: black;
    }
    /*low-res monitors*/
    @media screen and (max-width: 1368px) {}

    /*phone resolution*/
    @media screen and (max-width: 768px) {
        .about-wrapper p {
            width: 90%;
        }
    }
</style>

<div id="nav"> <?php \App\ViewModel\View::renderComponent('admin/nav.phtml') ?> </div>
<div class="about-wrapper">
    <div class="section-title">
        <h1><?= $blog->getId() ? 'Edit Blog' : 'New Blog' ?></h1>
    </div>
    <form method="post" action="/admin/blog/save?id=<?= $blog->getId() ?>" enctype="multipart/form-data">
        <label for="enabled">Enabled:</label>
        <input type="checkbox" id="enabled" name="enabled" <?= $blog->isEnabled() ? 'checked' : '' ?>>
        <br>

        <label for="title_form">Title:</label>
        <input type="text" id="title_form" name="title" value="<?= $blog->getTitle() ?>" required>
        <br>

        <label for="description_form">Description:</label>
        <input type="text" id="description_form" name="description" value="<?= $blog->getDescription() ?>">
        <br>

        <label for="blog_body">Body: </label>
        <textarea id="blog_body" name="blog_body">
            <?= $blog->getBody() ?>
        </textarea>

        <label for="title_form_ka">Title (KA):</label>
        <input type="text" id="title_form_ka" name="title_ka" value="<?= $blog->getTitle('ka') ?>" required>
        <br>

        <label for="description_form_ka">Description (KA):</label>
        <input type="text" id="description_form_ka" name="description_ka" value="<?= $blog->getDescription('ka') ?>">
        <br>

        <label for="blog_body_ka">Body (KA): </label>
        <textarea id="blog_body_ka" name="blog_body_ka">
            <?= $blog->getBody('ka') ?>
        </textarea>

        <h2>SEO</h2>

        <label for="meta_title">Meta Title</label>
        <input type="text" id="meta_title" name="meta_title" value="<?= $blog->getMetaTitle() ?>">
        <br>

        <label for="meta_keyword">Meta Keyword</label>
        <input type="text" id="meta_keyword" name="meta_keyword" value="<?= $blog->getMetaKeyword() ?>">
        <br>

        <label for="meta_description">Meta Description</label>
        <input type="text" id="meta_description" name="meta_description" value="<?= $blog->getMetaDescription() ?>">
        <br>

        <label for="meta_title_ka">Meta Title (KA):</label>
        <input type="text" id="meta_title_ka" name="meta_title_ka" value="<?= $blog->getMetaTitle('ka') ?>">
        <br>

        <label for="meta_keyword_ka">Meta Keyword (KA):</label>
        <input type="text" id="meta_keyword_ka" name="meta_keyword_ka" value="<?= $blog->getMetaKeyword('ka') ?>">
        <br>

        <label for="meta_description_ka">Meta Description (KA):</label>
        <input type="text" id="meta_description_ka" name="meta_description_ka" value="<?= $blog->getMetaDescription('ka') ?>">
        <br>

        <button type="submit" class="btn" name="<?= $blog->getId() ? 'update_blog' : 'create_blog' ?>">Save</button>
    </form>

    <?php if ($blog->getId()): ?>
        <form method="post" action="/admin/blog/delete?id=<?= $blog->getId() ?>">
            <button type="submit" class="btn">DELETE</button>
        </form>
    <?php endif; ?>

    <?php if ($blog->getId()): ?>
        <h2>Images</h2>
        <form method="POST" action="/admin/blog/upload?id=<?= $blog->getId() ?>" enctype="multipart/form-data">
            <h4>Thumbnail</h4>
            <input type="hidden" name="MAX_FILE_SIZE" value="1000000"/>

            <input type="hidden" name="blog_pic_id" value="<?= $image->getId() ?>"/>
            <input type="file" name="blog_pic" accept="image/*"/>
            <?= $image->toHtml(); ?>
            <br>

            <label for="blog_pic_title">Title:</label>
            <input type="text" id="blog_pic_title" name="blog_pic_title" value="<?= $image->getTitle() ?? '' ?>">
            <br>

            <label for="blog_pic_alt">Alt:</label>
            <input type="text" id="blog_pic_alt" name="blog_pic_alt" value="<?= $image->getAlt() ?? '' ?>">
            <br>

            <br>
            <br>

            <input type="submit" value="Save Images"/>
        </form>
    <?php endif; ?>
</div>
<div id="footer"></div>
</body>

</html>