<?php
/** @var App\Model\Product $product */
/** @var array $productOwners */
/** @var App\Model\Image $image */
/** @var App\Model\Image $logo */
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <title>Document</title>
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" type="text/javascript"></script>
    <script>
        $(function () {
            $("#footer").load("/templates/componenetns/footer.html");
        });
    </script>
</head>

<body>
<style>
    .about-wrapper {
        margin-top: 50px;
        width: 100%;
        min-height: 84vh;
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .about-wrapper .section-title h1 {
        border-bottom: 2px solid black;
    }

    .about-wrapper p {
        text-align: center;
        width: 40%;
        margin-bottom: 40px;
    }
    .team-member-wrapper{
        width: 100%;
        min-height: 60vh;
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        align-items: center;
        justify-content: space-evenly;
    }

    .box{
        margin: 15px;
        width: 300px;
        height: 300px;
        background-color: black;
    }
    /*low-res monitors*/
    @media screen and (max-width: 1368px) {}

    /*phone resolution*/
    @media screen and (max-width: 768px) {
        .about-wrapper p {
            width: 90%;
        }
    }
</style>

<div id="nav"> <?php \App\ViewModel\View::renderComponent('admin/nav.phtml') ?> </div>
<div class="about-wrapper">
    <div class="section-title">
        <h1><?= $product->getId() ? 'Edit Product' : 'New Product' ?></h1>
    </div>
    <form method="post" action="/admin/product/save?id=<?= $product->getId() ?>" enctype="multipart/form-data">
        <label for="name_form">Name:</label>
        <input type="text" id="name_form" name="name" maxlength="45" value="<?= $product->getName() ?>" required>
        <br><br><br>

        <label for="page_html">Page Html:</label>
        <textarea class="desc" id="page_html" name="page_html" ><?= $product->getPageHtml() ?></textarea>
        <br><br><br>

        <label for="full_description">Description: </label>
        <textarea id="full_description" name="description"><?= $product->getDescription() ?></textarea>
        <br><br><br>

        <label for="desc_form">Short Description:</label>
        <textarea class="desc" id="desc_form" name="short_description" maxlength="800"><?= $product->getShortDescription() ?></textarea>
        <br><br><br>

        <label for="name_form_ka">Name (KA):</label>
        <input type="text" id="name_form_ka" name="name_ka" maxlength="45" value="<?= $product->getName('ka') ?>" required>
        <br><br><br>

        <label for="page_html_ka">Page Html (KA):</label>
        <textarea class="desc" id="page_html_ka" name="page_html_ka" ><?= $product->getPageHtml('ka') ?></textarea>
        <br><br><br>

        <label for="full_description_ka">Description (KA): </label>
        <textarea id="full_description_ka" name="description_ka"><?= $product->getDescription('ka') ?></textarea>
        <br><br><br>

        <label for="desc_form_ka">Short Description (KA):</label>
        <textarea class="desc" id="desc_form_ka" name="short_description_ka" maxlength="800"><?= $product->getShortDescription('ka') ?></textarea>
        <br><br><br>

        <label for="owner_id">Product Owner:</label>
        <select name="owner_id" id="owner_id">
            <option value="-1">&lt;None&gt;</option>
            <?php /** @var App\Model\User $owner */ ?>
            <?php foreach ($productOwners as $owner): ?>
                <option value="<?= $owner->getId() ?>" <?= $owner->getId() == $product->getOwnerId() ? 'selected' : '' ?>>
                    <?= $owner->getName() ?>
                </option>
            <?php endforeach; ?>
        </select>
        <br><br><br>

        <h2>SEO</h2>

        <label for="meta_title">Meta Title</label>
        <input type="text" id="meta_title" name="meta_title" value="<?= $product->getMetaTitle() ?>">
        <br>

        <label for="meta_keyword">Meta Keyword</label>
        <input type="text" id="meta_keyword" name="meta_keyword" value="<?= $product->getMetaKeyword() ?>">
        <br>

        <label for="meta_description">Meta Description</label>
        <input type="text" id="meta_description" name="meta_description" value="<?= $product->getMetaDescription() ?>">
        <br>

        <label for="meta_title_ka">Meta Title (KA):</label>
        <input type="text" id="meta_title_ka" name="meta_title_ka" value="<?= $product->getMetaTitle('ka') ?>">
        <br>

        <label for="meta_keyword_ka">Meta Keyword (KA):</label>
        <input type="text" id="meta_keyword_ka" name="meta_keyword_ka" value="<?= $product->getMetaKeyword('ka') ?>">
        <br>

        <label for="meta_description_ka">Meta Description (KA):</label>
        <input type="text" id="meta_description_ka" name="meta_description_ka" value="<?= $product->getMetaDescription('ka') ?>">
        <br>

        <button class="dashboard-button" type="submit" class="btn" name="<?= $product->getId() ? 'update_product' : 'create_product' ?>">Save</button>
    </form>


    <?php if ($product->getId()): ?>
        <form method="post" action="/admin/product/delete?id=<?= $product->getId() ?>">
            <button class="dashboard-button" style="background-color: #ff0000;" type="submit" class="btn">Delete Product</button>
        </form>
        <h2>Images</h2>
        <form method="POST" action="/admin/product/upload?id=<?= $product->getId() ?>" enctype="multipart/form-data">
            <h4>Picture For Main Page</h4>
            <input type="hidden" name="MAX_FILE_SIZE" value="1000000"/>

            <input type="hidden" name="product_pic_id" value="<?= $product->getImage() ?>"/>
            <input type="file" name="product_pic" accept="image/*"/>
            <img class="admin-image-showcase" src="<?= $image->getValue() ?>" title="<?= $image->getTitle() ?>" alt="<?= $image->getAlt() ?>">
            <br>

            <label for="product_pic_title">Title:</label>
            <input type="text" id="product_pic_title" name="product_pic_title" value="<?= $image->getTitle() ?? '' ?>">
            <br>

            <label for="product_pic_alt">Alt:</label>
            <input type="text" id="product_pic_alt" name="product_pic_alt" value="<?= $image->getAlt() ?? '' ?>">
            <br>


            <h4>Logo</h4>
            <input type="hidden" name="product_logo_id" value="<?= $logo->getId() ?>"/>
            <input type="file" name="product_logo" accept="image/*"/>
            <img class="admin-image-showcase" src="<?= $logo->getValue() ?>" title="<?= $logo->getTitle() ?>" alt="<?= $logo->getAlt() ?>">
            <br>

            <label for="product_logo_title">Title:</label>
            <input type="text" id="product_logo_title" name="product_logo_title" value="<?= $logo->getTitle() ?? '' ?>">
            <br>

            <label for="product_logo_alt">Alt:</label>
            <input type="text" id="product_logo_alt" name="product_logo_alt" value="<?= $logo->getAlt() ?? '' ?>">
            <br>

            <br>
            <br>

            <input class="dashboard-button" type="submit" value="Save Images"/>
        </form>
    <?php endif; ?>
</div>
<div id="footer"></div>
</body>

</html>