<?php
/** @var App\Model\Project $project */
/** @var App\Model\Image $image */
/** @var App\Model\Image $logo */
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <title>Document</title>
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" type="text/javascript"></script>
    <script>
        $(function () {
            $("#footer").load("/templates/componenetns/footer.html");
        });
    </script>
</head>

<body>
<style>
    .about-wrapper {
        margin-top: 50px;
        width: 100%;
        min-height: 84vh;
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .about-wrapper .section-title h1 {
        border-bottom: 2px solid black;
    }

    .about-wrapper p {
        text-align: center;
        width: 40%;
        margin-bottom: 40px;
    }
    .team-member-wrapper{
        width: 100%;
        min-height: 60vh;
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        align-items: center;
        justify-content: space-evenly;
    }

    .box{
        margin: 15px;
        width: 300px;
        height: 300px;
        background-color: black;
    }
    /*low-res monitors*/
    @media screen and (max-width: 1368px) {}

    /*phone resolution*/
    @media screen and (max-width: 768px) {
        .about-wrapper p {
            width: 90%;
        }
    }
</style>

<div id="nav"> <?php \App\ViewModel\View::renderComponent('admin/nav.phtml') ?> </div>
<div class="about-wrapper">
    <div class="section-title">
        <h1><?= $project->getId() ? 'Edit Project' : 'New Project' ?></h1>
    </div>
    <form method="post" action="/admin/project/save?id=<?= $project->getId() ?>" enctype="multipart/form-data">
        <label for="name_form">Name:</label>
        <input type="text" id="name_form" name="name" maxlength="100" value="<?= $project->getName() ?>" required>
        <br>

        <label for="desc_form">Description: </label>
        <textarea class="desc" id="desc_form" name="short_description" maxlength="300" ><?= $project->getShortDescription() ?></textarea>
        <br>

        <label for="full_description">Project Text: </label>
        <textarea id="full_description" name="description"><?= $project->getDescription() ?></textarea>
        <br>

        <label for="slider_html">Slider HTML: </label>
        <textarea id="slider_html" name="slider_html"><?= $project->getSliderHtml() ?></textarea>
        <br>

        <label for="name_form_ka">Name (KA):</label>
        <input type="text" id="name_form_ka" name="name_ka" maxlength="100" value="<?= $project->getName('ka') ?>" required>
        <br>

        <label for="desc_form_ka">Description (KA): </label>
        <textarea class="desc" id="desc_form_ka" name="short_description_ka" maxlength="300" ><?= $project->getShortDescription('ka') ?></textarea>
        <br>

        <label for="full_description_ka">Project Text (KA): </label>
        <textarea id="full_description_ka" name="description_ka"><?= $project->getDescription('ka') ?></textarea>
        <br>

        <label for="slider_html_ka">Slider HTML (KA): </label>
        <textarea id="slider_html_ka" name="slider_html_ka"><?= $project->getSliderHtml('ka') ?></textarea>
        <br>

        <h2>SEO</h2>

        <label for="meta_title">Meta Title</label>
        <input type="text" id="meta_title" name="meta_title" value="<?= $project->getMetaTitle() ?>">
        <br>

        <label for="meta_keyword">Meta Keyword</label>
        <input type="text" id="meta_keyword" name="meta_keyword" value="<?= $project->getMetaKeyword() ?>">
        <br>

        <label for="meta_description">Meta Description</label>
        <input type="text" id="meta_description" name="meta_description" value="<?= $project->getMetaDescription() ?>">
        <br>

        <label for="meta_title_ka">Meta Title (KA):</label>
        <input type="text" id="meta_title_ka" name="meta_title_ka" value="<?= $project->getMetaTitle('ka') ?>">
        <br>

        <label for="meta_keyword_ka">Meta Keyword (KA):</label>
        <input type="text" id="meta_keyword_ka" name="meta_keyword_ka" value="<?= $project->getMetaKeyword('ka') ?>">
        <br>

        <label for="meta_description_ka">Meta Description (KA):</label>
        <input type="text" id="meta_description_ka" name="meta_description_ka" value="<?= $project->getMetaDescription('ka') ?>">
        <br>

        <button type="submit" class="btn" name="<?= $project->getId() ? 'update_project' : 'create_project' ?>">Save</button>
    </form>


    <?php if ($project->getId()): ?>
        <form method="post" action="/admin/project/delete?id=<?= $project->getId() ?>">
            <button type="submit" class="btn">Delete Project</button>
        </form>
        <h2>Images</h2>
        <form method="POST" action="/admin/project/upload?id=<?= $project->getId() ?>" enctype="multipart/form-data">
            <h4>Picture</h4>
            <input type="hidden" name="MAX_FILE_SIZE" value="1000000"/>

            <input type="hidden" name="project_pic_id" value="<?= $project->getImage() ?>"/>
            <input type="file" name="project_pic" accept="image/*"/>
            <img src="<?= $image->getValue() ?>" title="<?= $image->getTitle() ?>" alt="<?= $image->getAlt() ?>">
            <br>

            <label for="project_pic_title">Title:</label>
            <input type="text" id="project_pic_title" name="project_pic_title" value="<?= $image->getTitle() ?? '' ?>">
            <br>

            <label for="project_pic_alt">Alt:</label>
            <input type="text" id="project_pic_alt" name="project_pic_alt" value="<?= $image->getAlt() ?? '' ?>">
            <br>


            <h4>Background For Listing </h4>
            <input type="hidden" name="project_logo_id" value="<?= $logo->getId() ?>"/>
            <input type="file" name="project_logo" accept="image/*"/>
            <img src="<?= $logo->getValue() ?>" title="<?= $logo->getTitle() ?>" alt="<?= $logo->getAlt() ?>">
            <br>

            <label for="project_logo_title">Title:</label>
            <input type="text" id="project_logo_title" name="project_logo_title" value="<?= $logo->getTitle() ?? '' ?>">
            <br>

            <label for="project_logo_alt">Alt:</label>
            <input type="text" id="project_logo_alt" name="project_logo_alt" value="<?= $logo->getAlt() ?? '' ?>">
            <br>

            <br>
            <br>

            <input type="submit" value="Save Images"/>
        </form>
    <?php endif; ?>
</div>
<div id="footer"></div>
</body>

</html>