<?php
/** @var App\Model\Service $service */
/** @var App\Model\Image $image */
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <title>Document</title>
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" type="text/javascript"></script>
    <script>
        $(function () {
            $("#footer").load("/templates/componenetns/footer.html");
        });
    </script>
</head>

<body>
<style>
    .about-wrapper {
        margin-top: 50px;
        width: 100%;
        min-height: 84vh;
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .about-wrapper .section-title h1 {
        border-bottom: 2px solid black;
    }

    .about-wrapper p {
        text-align: center;
        width: 40%;
        margin-bottom: 40px;
    }
    .team-member-wrapper{
        width: 100%;
        min-height: 60vh;
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        align-items: center;
        justify-content: space-evenly;
    }

    .box{
        margin: 15px;
        width: 300px;
        height: 300px;
        background-color: black;
    }
    /*low-res monitors*/
    @media screen and (max-width: 1368px) {}

    /*phone resolution*/
    @media screen and (max-width: 768px) {
        .about-wrapper p {
            width: 90%;
        }
    }
</style>

<div id="nav"> <?php \App\ViewModel\View::renderComponent('admin/nav.phtml') ?> </div>
<div class="about-wrapper">
    <div class="section-title">
        <h1><?= $service->getId() ? 'Edit Service' : 'New Service' ?></h1>
    </div>
    <form method="post" action="/admin/service/save?id=<?= $service->getId() ?>" enctype="multipart/form-data">
        <label for="title_form">Name:</label>
        <input type="text" id="title_form" name="title" value="<?= $service->getTitle() ?>" required>
        <br>

        <label for="title_form_ka">Name (KA):</label>
        <input type="text" id="title_form_ka" name="title_ka" value="<?= $service->getTitle('ka') ?>" required>
        <br>

        <button type="submit" class="btn" name="<?= $service->getId() ? 'update_service' : 'create_service' ?>">Save</button>
    </form>


    <?php if ($service->getId()): ?>
        <form method="post" action="/admin/service/delete?id=<?= $service->getId() ?>">
            <button type="submit" class="btn">Delete Service</button>
        </form>
        <h2>Images</h2>
        <form method="POST" action="/admin/service/upload?id=<?= $service->getId() ?>" enctype="multipart/form-data">
            <h4>Picture</h4>
            <input type="hidden" name="MAX_FILE_SIZE" value="1000000"/>

            <input type="hidden" name="service_pic_id" value="<?= $service->getImage() ?>"/>
            <input type="file" name="service_pic" accept="image/*"/>
            <img src="<?= $image->getValue() ?>" title="<?= $image->getTitle() ?>" alt="<?= $image->getAlt() ?>">
            <br>

            <label for="service_pic_title">Title:</label>
            <input type="text" id="service_pic_title" name="service_pic_title" value="<?= $image->getTitle() ?? '' ?>">
            <br>

            <label for="service_pic_alt">Alt:</label>
            <input type="text" id="service_pic_alt" name="service_pic_alt" value="<?= $image->getAlt() ?? '' ?>">
            <br>
            <br>

            <input type="submit" value="Save Images"/>
        </form>
    <?php endif; ?>
</div>
<div id="footer"></div>
</body>

</html>