<?php
/** @var App\Model\User $user */
/** @var App\Model\Image $image */
/** @var App\Model\Image $gif */
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <title>Document</title>
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" type="text/javascript"></script>
    <script>
        $(function () {
            $("#nav").load("/templates/componenetns/admin/nav.phtml");
            $("#footer").load("/templates/componenetns/footer.html");
        });
    </script>
</head>

<body>
<style>
    .about-wrapper {
        margin-top: 50px;
        width: 100%;
        min-height: 84vh;
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .about-wrapper .section-title h1 {
        border-bottom: 2px solid black;
    }

    .about-wrapper p {
        text-align: center;
        width: 40%;
        margin-bottom: 40px;
    }
    .team-member-wrapper{
        width: 100%;
        min-height: 60vh;
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        align-items: center;
        justify-content: space-evenly;
    }

    .box{
        margin: 15px;
        width: 300px;
        height: 300px;
        background-color: black;
    }
    /*low-res monitors*/
    @media screen and (max-width: 1368px) {}

    /*phone resolution*/
    @media screen and (max-width: 768px) {
        .about-wrapper p {
            width: 90%;
        }
    }
</style>

<div id="nav"></div>
<div class="about-wrapper">
    <div class="section-title">
        <h1><?= $user->getId() ? 'Edit Product Owner' : 'Create New Product Owner' ?></h1>
    </div>
    <form method="post" action="/admin/user/save?id=<?= $user->getId() ?>" enctype="multipart/form-data">
        <label for="enabled">Enabled:</label>
        <input type="checkbox" id="enabled" name="enabled" <?= $user->isEnabled() ? 'checked' : '' ?>>
        <br>

        <label for="name_form">Full Name:</label>
        <input type="text" id="name_form" name="name" value="<?= $user->getName() ?>" required>
        <br>

        <label for="full_description">Full Description: </label>
        <textarea id="full_description" name="description"><?= $user->getDescription() ?></textarea>
        <br>

        <label for="desc_form">Short Description</label>
        <textarea class="desc" id="desc_form" name="short_description"><?= $user->getShortDescription() ?></textarea>
        <br>

        <label for="is_owner">Is Product Owner:</label>
        <input type="checkbox" id="is_owner" name="is_owner" <?= $user->isProductOwner() ? 'checked' : '' ?>>
        <br>

        <button type="submit" class="btn" name="<?= $user->getId() ? 'update_user' : 'create_user' ?>">Save User</button>
    </form>

    <?php if ($user->getId()): ?>
        <form method="post" action="/admin/user/delete?id=<?= $user->getId() ?>">
            <button type="submit" class="btn">Delete User</button>
        </form>
        <h2>Images</h2>
        <form method="POST" action="/admin/user/upload?id=<?= $user->getId() ?>" enctype="multipart/form-data">
            <h4>Profile picture</h4>
            <input type="hidden" name="MAX_FILE_SIZE" value="1000000"/>

            <input type="hidden" name="user_pic_id" value="<?= $image->getId() ?>"/>
            <input type="file" name="user_pic" accept="image/*"/>
            <?= $image->toHtml(); ?>
            <br>

            <label for="user_pic_title">Title:</label>
            <input type="text" id="user_pic_title" name="user_pic_title" value="<?= $image->getTitle() ?? '' ?>">
            <br>

            <label for="user_pic_alt">Alt:</label>
            <input type="text" id="user_pic_alt" name="user_pic_alt" value="<?= $image->getAlt() ?? '' ?>">
            <br>


            <h4>Gif Image</h4>
            <input type="hidden" name="user_gif_id" value="<?= $gif->getId() ?>"/>
            <input type="file" name="user_gif" accept="image/*"/>
            <?= $gif->toHtml(); ?>
            <br>

            <label for="user_gif_title">Title:</label>
            <input type="text" id="user_gif_title" name="user_gif_title" value="<?= $gif->getTitle() ?? '' ?>">
            <br>

            <label for="user_gif_alt">Alt:</label>
            <input type="text" id="user_gif_alt" name="user_gif_alt" value="<?= $gif->getAlt() ?? '' ?>">
            <br>

            <br>
            <br>

            <input type="submit" value="Save Images"/>
        </form>
    <?php endif; ?>
</div>
<div id="footer"></div>
</body>

</html>